---
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/clover-example
    steps:
      - checkout
      - restore_cache:
          keys:
          - clover-example-{{ checksum "pom.xml" }}
      - run: mvn -P test dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: clover-example-{{ checksum "pom.xml" }}
      - run: mvn -P test integration-test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/clover-example-1.0-SNAPSHOT.jar
